# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2cbd8190f3bae59f3857d9569f6ec2a7ead9f36e307f9ce9a8528ae6071c882ab625ffb703c748c20483319730ace6a9b6f86394b0ad39bec8d1c9df054d6ce

test:
  secret_key_base: 2ae2a9a2e2019e93e73a459152e5c7215c7d8a79370f9866a645375d6386ad8c119569ec1a585417712c175aaf246c61a6959b78c9397ff5e847632c68e30561

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
